---
title: "hw5"
author: "Shan Jiang"
date: "11/2/2018"
output: github_document
---
```{r}
library(tidyverse)
library(rvest)

set.seed(1)
```

## Problem 1

Inspecting the file path and file names in the zip.
```{r}
file_path <- "./data/"
length(list.files(file_path))  # How many files are there?
list.files(file_path)  # Show all names
list.files(file_path)[11:20]  # Show last 10 names

```

Create a tidy dataframe containing data from all participants, including the subject ID, arm, and observations over time.


### Construct a dataframe using the `list.files` function
```{r}
## Construct a function to read the csv file
read_sheet <- function(path) {
   df = readr::read_csv(path) %>% 
   janitor::clean_names()
   
   df
}

## Construct the path 

base = "./data/"
p = list.files(file_path)[1:10] 
vec_name = str_c(base, c(p))

control_df = map_df(vec_name, read_sheet)

```

* Tidy the result: file names include the subject ID and arm.
```{r}
control_df = control_df %>% 
  mutate(ID = as.factor(1:10), Group = "control" ) %>% 
  select(Group, ID, week_1:week_8) 
```

### Spaghetti plot 
```{r}

```


* Comment on differences between groups.


## Problem 2

```{r}

```


